### ISSUE TITLE
stuck at npm intall when cd to DocuHash

### ISSUE THREAD

**Issue by Csyoung29** [FutureProcessing/DocuHash#2]
![image](https://user-images.githubusercontent.com/28551146/66272571-f6d25600-e89d-11e9-8a14-56194f242e03.png)

C:\DocuHash>npm start

> docuhash@1.0.0 start C:\DocuHash
> node server.js

You can improve web3's peformance when running Node.js versions older than 10.5.0 by installing the (deprecated) scrypt package in your project
module.js:550
    throw err;
    ^

Error: Cannot find module './../build/contracts/HashStorage.json'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\DocuHash\services\hs-contract-provider.js:2:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\DocuHash\services\hs-service.js:1:82)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\DocuHash\server.js:7:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! docuhash@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the docuhash@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2019-10-06T16_59_52_574Z-debug.log

**Comment by elkorba** [comment]
It looks like your contracts were not built or you just missed the contract migration step.
Check the above-mentioned folder /build/contracts/ if it doesn't exist then it is confirmed that contracts haven't been built.

**Comment by Csyoung29** [comment]
Thank you! How to do the contract migration step?

**Comment by elkorba** [comment]
[As described here](https://www.future-processing.pl/blog/storing-files-in-a-distributed-file-system-using-blockchain-technology/) point C.6 which opens up the truffle console and then C.7 which migrates contracts. Follow these steps to successfully set up the project.

**Comment by Csyoung29** [comment]
Sorry about wrong info, I had changed my title.  I stucked at C.4 ~npm install not D.2 npm start. How is the solution？

**Comment by elkorba** [comment]
You have to ensure that your environment is properly configured. 
If you have all the components installed (node, IPFS) then you can move to the project compilation.
If npm install doesn't work you have to analyse error message and approach it properly, in most cases, the environment lacks windows build tools (of course if you are windows user).
It is hard to help you without any details.
